trigger:
  batch: true
  branches:
    include:
    - develop
    - staging
    - master
    - ops/*
  paths:
    exclude:
    -  docs/*
pr: none
resources:
  - repo: self

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
  Docker.filePath: "**/docker/Dockerfile.local"
  Docker.repository: "flex-registration"
  Docker.registry: "unihopeukrsrdev"
  azureSubscription: "uni-hope-ukr-sr-dev"

stages:
  - stage: build_and_push
    displayName: BUILD and PUSH
    jobs:
      - job: build_push_backend
        pool:
          vmImage: ubuntu-latest
        displayName: "[APP]"
        steps:
          - task: Docker@2
            displayName: Build&Push
            inputs:
              command: buildAndPush
              buildContext: "**/.."
              dockerfile: $(Docker.filePath)
              repository: $(Docker.repository)
              containerRegistry: $(Docker.registry)
              tags: |
                $(Build.BuildId)
                $(Build.SourceVersion)
  - stage: deploy
    displayName: Deploy
    jobs:
      - job: deploy_backend
        pool:
          vmImage: ubuntu-latest
        displayName: "Deploy app"
        steps:
          - task: AzureWebAppContainer@1
            displayName: Azure Web App on Container Deploy
            inputs:
              appName: webappforcontainers
              azureSubscription: $(azureSubscription)
              imageName: $(Docker.registry).azurecr.io/$(Docker.repository):$(Build.SourceVersion)
