trigger:
  batch: true
  branches:
    include:
    - develop
    - master
    - ops/*
pr: none
resources:
  - repo: self

variables:
  - group: flex-registration-dev
  - name: Docker.filePath
    value: "**/docker/Dockerfile"
  - name: Docker.repository
    value: "flex-registration"
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    - name: Docker.registry
      value: "unihopeukrsr"
    - name: azureSubscription
      value: "UNI_WEBS rs-uni-hope-ukr-sr"
    - name: appName
      value: "uni-hope-ukr-sr"
  - ${{ else }}:
    - name: Docker.registry
      value: "unihopeukrsrdev"
    - name: azureSubscription
      value: "UNI_WEBS rs-uni-hope-ukr-sr-dev"
    - name: appName
      value: "uni-hope-ukr-sr-dev"

stages:
  - stage: build_and_push
    displayName: BUILD and PUSH $(Build.SourceBranchName)
    jobs:
      - job: build_push_backend
        pool:
          vmImage: ubuntu-latest
        displayName: "Build and Push"
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(Docker.registry)'
              command: 'login'
          - script: "docker pull $(Docker.registry).azurecr.io/$(Docker.repository):latest"
            displayName: Pull latest for layer caching
            continueOnError: true # for first build, no cache
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              dockerfile: $(Docker.filePath)
              repository: $(Docker.repository)
              buildContext: "**/.."
              arguments: '--cache-from=$(Docker.registry).azurecr.io/$(Docker.repository):latest'
              tags: |
                $(Build.BuildId)
                $(Build.SourceVersion)
                latest
          - task: Docker@2
            displayName: Push
            inputs:
              command: Push
              buildContext: "**/.."
              dockerfile: $(Docker.filePath)
              repository: $(Docker.repository)
              containerRegistry: $(Docker.registry)
              tags: |
                $(Build.BuildId)
                $(Build.SourceVersion)
                latest
  - stage: deploy
    displayName: Deploy
    jobs:
      - job: deploy_backend
        pool:
          vmImage: ubuntu-latest
        displayName: "Deploy app"
        steps:
          - task: AzureWebAppContainer@1
            displayName: Azure Web App on Container Deploy
            inputs:
              appName: $(appName)
              azureSubscription: $(azureSubscription)
              imageName: $(Docker.registry).azurecr.io/$(Docker.repository):$(Build.SourceVersion)
              appSettings: "-PYTHONPATH $(PYTHONPATH)
              -ALLOWED_HOSTS $(ALLOWED_HOSTS)
              -AUTHENTICATION_BACKENDS $(AUTHENTICATION_BACKENDS)
              -SECRET_KEY $(SECRET_KEY)
              -ADMIN_EMAIL $(ADMIN_EMAIL)
              -ADMIN_PASSWORD $(ADMIN_PASSWORD)
              -DEBUG $(DEBUG)
              "
